"""add broadcast jobs, logs, media

Revision ID: 6142947c97aa
Revises: e504e6e4457a
Create Date: 2026-04-21 23:20:27.680215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6142947c97aa'
down_revision: Union[str, None] = 'e504e6e4457a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['mensageria.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('broadcast_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('audience_type', sa.String(length=30), nullable=False),
    sa.Column('audience_spec', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('message_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['mensageria.channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['mensageria.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flow_id'], ['mensageria.chatbot_flows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('broadcast_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('target_wa_id', sa.String(length=100), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['mensageria.broadcast_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_index(op.f('ix_mensageria_broadcast_logs_job_id'), 'broadcast_logs', ['job_id'], unique=False, schema='mensageria')
    op.create_index(op.f('ix_mensageria_broadcast_logs_sent_at'), 'broadcast_logs', ['sent_at'], unique=False, schema='mensageria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensageria_broadcast_logs_sent_at'), table_name='broadcast_logs', schema='mensageria')
    op.drop_index(op.f('ix_mensageria_broadcast_logs_job_id'), table_name='broadcast_logs', schema='mensageria')
    op.drop_table('broadcast_logs', schema='mensageria')
    op.drop_table('broadcast_jobs', schema='mensageria')
    op.drop_table('media_assets', schema='mensageria')
    # ### end Alembic commands ###
