"""initial schema

Revision ID: 945d7ae24350
Revises: 
Create Date: 2026-04-21 20:12:26.212602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '945d7ae24350'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default='{"nodes":[],"edges":[]}', nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_number_id', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_token', sa.Text(), nullable=True),
    sa.Column('waba_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('instance_name', sa.String(length=100), nullable=True),
    sa.Column('instance_token', sa.Text(), nullable=True),
    sa.Column('page_id', sa.String(length=50), nullable=True),
    sa.Column('instagram_id', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('operation_mode', sa.String(length=20), nullable=False),
    sa.Column('active_chatbot_flow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_chatbot_flow_id'], ['mensageria.chatbot_flows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('automation_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['mensageria.channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('chatbot_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('contact_wa_id', sa.String(length=100), nullable=False),
    sa.Column('current_node_id', sa.String(length=100), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['mensageria.channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_id'], ['mensageria.chatbot_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_index(op.f('ix_mensageria_chatbot_sessions_contact_wa_id'), 'chatbot_sessions', ['contact_wa_id'], unique=False, schema='mensageria')
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('lead_status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_active', sa.Boolean(), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(), nullable=True),
    sa.Column('reengagement_count', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('deal_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ai_memory', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('ai_memory_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['mensageria.channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_index(op.f('ix_mensageria_contacts_wa_id'), 'contacts', ['wa_id'], unique=True, schema='mensageria')
    op.create_table('automation_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('contact_wa_id', sa.String(length=100), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_send_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['mensageria.automation_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('automation_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['mensageria.automation_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('chatbot_scheduled_resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('resume_at', sa.DateTime(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mensageria.chatbot_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wa_message_id', sa.String(length=255), nullable=False),
    sa.Column('contact_wa_id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_by_ai', sa.Boolean(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['mensageria.channels.id'], ),
    sa.ForeignKeyConstraint(['contact_wa_id'], ['mensageria.contacts.wa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mensageria'
    )
    op.create_index(op.f('ix_mensageria_messages_contact_wa_id'), 'messages', ['contact_wa_id'], unique=False, schema='mensageria')
    op.create_index(op.f('ix_mensageria_messages_wa_message_id'), 'messages', ['wa_message_id'], unique=True, schema='mensageria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensageria_messages_wa_message_id'), table_name='messages', schema='mensageria')
    op.drop_index(op.f('ix_mensageria_messages_contact_wa_id'), table_name='messages', schema='mensageria')
    op.drop_table('messages', schema='mensageria')
    op.drop_table('chatbot_scheduled_resumes', schema='mensageria')
    op.drop_table('automation_steps', schema='mensageria')
    op.drop_table('automation_executions', schema='mensageria')
    op.drop_index(op.f('ix_mensageria_contacts_wa_id'), table_name='contacts', schema='mensageria')
    op.drop_table('contacts', schema='mensageria')
    op.drop_index(op.f('ix_mensageria_chatbot_sessions_contact_wa_id'), table_name='chatbot_sessions', schema='mensageria')
    op.drop_table('chatbot_sessions', schema='mensageria')
    op.drop_table('automation_flows', schema='mensageria')
    op.drop_table('channels', schema='mensageria')
    op.drop_table('chatbot_flows', schema='mensageria')
    # ### end Alembic commands ###
